// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjdIZ8pJ68bw2elu7_c4QU5AZh53ZZqHU',
    appId: '1:843317433006:web:5576e79dca1faaa247133f',
    messagingSenderId: '843317433006',
    projectId: 'chat-app-8a791',
    authDomain: 'chat-app-8a791.firebaseapp.com',
    storageBucket: 'chat-app-8a791.appspot.com',
    measurementId: 'G-BLFNLKNDRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxL2WwbY7SnVWGnCFJcnMXk2A6z6Q9eSA',
    appId: '1:843317433006:android:11ca96880d7ead8547133f',
    messagingSenderId: '843317433006',
    projectId: 'chat-app-8a791',
    storageBucket: 'chat-app-8a791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1XdCJg0zRq5tqj9H5kLiSc8Qrynz3Z4',
    appId: '1:843317433006:ios:64f6cf5062817adf47133f',
    messagingSenderId: '843317433006',
    projectId: 'chat-app-8a791',
    storageBucket: 'chat-app-8a791.appspot.com',
    iosClientId: '843317433006-t0qk54j7bosi7l08fe3bokh6im5pavqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV1XdCJg0zRq5tqj9H5kLiSc8Qrynz3Z4',
    appId: '1:843317433006:ios:5a15dd90d5d706a047133f',
    messagingSenderId: '843317433006',
    projectId: 'chat-app-8a791',
    storageBucket: 'chat-app-8a791.appspot.com',
    iosClientId: '843317433006-dgngv3ri04qckm62fvpdudcb0t94mvm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp2.RunnerTests',
  );
}
